"""Create Full DataBase

Revision ID: 1f231f5f73c0
Revises: 
Create Date: 2026-02-21 20:12:33.076111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f231f5f73c0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('discount_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('full_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('clothing_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand', 'clothing_id', name='unique_id_clothing_per_brand')
    )
    op.create_table('users',
    sa.Column('google_id', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('subplain', sa.Enum('free', 'basic', name='subplains'), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('google_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id')
    )
    op.create_table('bots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('bot_token', sa.String(length=300), nullable=False),
    sa.Column('chat_id', sa.String(length=100), nullable=False),
    sa.Column('stores', sa.String(), nullable=True),
    sa.Column('affiliate_link', sa.String(length=300), nullable=True),
    sa.Column('sent_time', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('active', 'paused', name='statusbot'), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.google_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('abacatepay_id', sa.String(length=200), nullable=True),
    sa.Column('abacatepay_customer', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('active', 'canceled', 'expired', 'pending', name='statussubplains'), nullable=True),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('start', sa.Date(), nullable=True),
    sa.Column('next_payment', sa.Date(), nullable=True),
    sa.Column('canceled_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.google_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abacatepay_id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    op.drop_table('bots')
    op.drop_table('users')
    op.drop_table('products')
    # ### end Alembic commands ###
