"""trocando store id por brand

Revision ID: 21e0e137bfc4
Revises: 44ae791f28f6
Create Date: 2026-03-03 22:43:14.433801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21e0e137bfc4'
down_revision: Union[str, Sequence[str], None] = '44ae791f28f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('stores_name_key'), 'stores', type_='unique')
    op.drop_column('stores', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('stores_name_key'), 'stores', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
