"""trocando store id por brand

Revision ID: 44ae791f28f6
Revises: 
Create Date: 2026-03-03 18:02:36.281203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44ae791f28f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_chat_ids',
    sa.Column('google_id', sa.String(), nullable=False),
    sa.Column('chat_id', sa.String(length=100), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('google_id')
    )
    op.create_table('stores',
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('platform', sa.Enum('shopify', 'nuvemshop', name='platform'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('brand'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('google_id', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('subplain', sa.Enum('free', 'freemium', 'premium', name='subplains'), nullable=False),
    sa.Column('trial_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('google_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('bots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('bot_token', sa.String(length=300), nullable=False),
    sa.Column('chat_id', sa.String(length=100), nullable=False),
    sa.Column('affiliate_link', sa.String(length=300), nullable=True),
    sa.Column('today_sent', sa.Integer(), nullable=False),
    sa.Column('all_sent', sa.Integer(), nullable=False),
    sa.Column('last_reset_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('active', 'paused', name='statusbot'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.google_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bots_user_id'), 'bots', ['user_id'], unique=True)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('billing_id', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.Enum('pix', 'card', name='paymentmethod'), nullable=True),
    sa.Column('plan', sa.Enum('monthly', 'annual', name='plantype'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.google_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_billing_id'), 'payments', ['billing_id'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('size', sa.String(length=100), nullable=True),
    sa.Column('discount_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('full_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('clothing_id', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand'], ['stores.brand'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand', 'clothing_id', name='uq_clothing_per_store')
    )
    op.create_index(op.f('ix_products_brand'), 'products', ['brand'], unique=False)
    op.create_index('ix_products_store_available_price', 'products', ['brand', 'available', 'discount_price'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('billing_id', sa.String(length=200), nullable=False),
    sa.Column('customer_id', sa.String(length=200), nullable=True),
    sa.Column('payment_method', sa.Enum('pix', 'card', name='paymentmethod'), nullable=True),
    sa.Column('plan', sa.Enum('monthly', 'annual', name='plantype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'canceled', 'expired', name='statussubplains'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_payment', sa.DateTime(timezone=True), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.google_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('billing_id')
    )
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=True)
    op.create_table('bot_stores',
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['brand'], ['stores.brand'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bot_id', 'brand')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bot_stores')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('ix_products_store_available_price', table_name='products')
    op.drop_index(op.f('ix_products_brand'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_billing_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_bots_user_id'), table_name='bots')
    op.drop_table('bots')
    op.drop_table('users')
    op.drop_table('stores')
    op.drop_table('pending_chat_ids')
    # ### end Alembic commands ###
