"""fix date defaults

Revision ID: 4ffe110fef62
Revises: 6fd7e932ce6b
Create Date: 2026-02-23 22:47:28.122664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ffe110fef62'
down_revision: Union[str, Sequence[str], None] = '6fd7e932ce6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('today_sent', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('bots', sa.Column('all_sent', sa.Integer(), nullable=False, server_default="0"))
    op.drop_column('bots', 'sent_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('sent_time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('bots', 'all_sent')
    op.drop_column('bots', 'today_sent')
    # ### end Alembic commands ###
