"""time to sent bot default 12 hrs

Revision ID: 595ed4b3bb23
Revises: fc9e0bf7aa2a
Create Date: 2026-03-07 23:32:06.397671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '595ed4b3bb23'
down_revision: Union[str, Sequence[str], None] = 'fc9e0bf7aa2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
