"""voltando limite de chracter e mudando para text da table ML

Revision ID: 6dcf6650b7b9
Revises: 6d0bff545853
Create Date: 2026-03-06 15:17:00.201929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dcf6650b7b9'
down_revision: Union[str, Sequence[str], None] = '6d0bff545853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ml_products', 'link',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_unique_constraint('uq_ml_item_id', 'ml_products', ['ml_item_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_ml_item_id', 'ml_products', type_='unique')
    op.alter_column('ml_products', 'link',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###
