"""botstore_bot_id

Revision ID: 7d01465d0877
Revises: 8b2fabc24f65
Create Date: 2026-03-05 11:22:20.482713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d01465d0877'
down_revision: Union[str, Sequence[str], None] = '8b2fabc24f65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_stores', sa.Column('bot_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('bot_stores_user_id_bot_fkey'), 'bot_stores', type_='foreignkey')
    op.create_foreign_key(None, 'bot_stores', 'bots', ['bot_id'], ['id'], ondelete='CASCADE')
    op.drop_column('bot_stores', 'user_id_bot')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_stores', sa.Column('user_id_bot', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bot_stores', type_='foreignkey')
    op.create_foreign_key(op.f('bot_stores_user_id_bot_fkey'), 'bot_stores', 'bots', ['user_id_bot'], ['user_id'], ondelete='CASCADE')
    op.drop_column('bot_stores', 'bot_id')
    # ### end Alembic commands ###
