"""table ML

Revision ID: af9a97815ec1
Revises: dc7912bf1174
Create Date: 2026-03-06 15:11:56.776934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af9a97815ec1'
down_revision: Union[str, Sequence[str], None] = 'dc7912bf1174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ml_item_id', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('discount_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('full_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ml_item_id')
    )
    op.create_index(op.f('ix_ml_products_category'), 'ml_products', ['category'], unique=False)
    op.create_index('ix_ml_products_category_discount', 'ml_products', ['category', 'discount_pct'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ml_products_category_discount', table_name='ml_products')
    op.drop_index(op.f('ix_ml_products_category'), table_name='ml_products')
    op.drop_table('ml_products')
    # ### end Alembic commands ###
