"""ML enum

Revision ID: dc7912bf1174
Revises: 7d01465d0877
Create Date: 2026-03-05 15:04:41.266766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc7912bf1174'
down_revision: Union[str, Sequence[str], None] = '7d01465d0877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE platform ADD VALUE 'mercadolivre'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
