"""Create sent_at

Revision ID: e52e3177e711
Revises: 1f231f5f73c0
Create Date: 2026-02-21 22:37:50.227292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e52e3177e711'
down_revision: Union[str, Sequence[str], None] = '1f231f5f73c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sent_at', sa.Date(), nullable=True))
    op.create_unique_constraint(None, 'users', ['google_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('products', 'sent_at')
    # ### end Alembic commands ###
