"""time to sent bot

Revision ID: fc9e0bf7aa2a
Revises: 6dcf6650b7b9
Create Date: 2026-03-07 23:22:44.282634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc9e0bf7aa2a'
down_revision: Union[str, Sequence[str], None] = '6dcf6650b7b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('time_to_sent', sa.Time(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bots', 'time_to_sent')
    # ### end Alembic commands ###
